# Generated by Django 4.0.3 on 2022-04-24 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('nid', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=128)),
                ('contact', models.CharField(max_length=15, null=True)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
                ('is_spot_owner', models.CharField(choices=[('R', 'Rentee'), ('S', 'Spot Owner')], default='user', max_length=10)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ParkingSlots',
            fields=[
                ('slot_id', models.CharField(max_length=30, primary_key=True, serialize=False, unique=True)),
                ('house', models.CharField(max_length=200)),
                ('area', models.CharField(max_length=200)),
                ('street', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Rentee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(max_length=200)),
                ('rentee_credit', models.IntegerField()),
                ('nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SpotOwner',
            fields=[
                ('nid', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('is_spot_owner', models.CharField(choices=[('R', 'Rentee'), ('S', 'Spot Owner')], default='user', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Rentee_Reviews_ParkingSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200)),
                ('rating', models.CharField(max_length=200)),
                ('rentee_nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rentee')),
                ('slot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.parkingslots')),
            ],
        ),
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rentee_credit', models.IntegerField()),
                ('nid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.rentee')),
            ],
        ),
        migrations.AddField(
            model_name='parkingslots',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.spotowner'),
        ),
    ]
