# Generated by Django 4.0.4 on 2022-04-26 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_slots', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ParkingTimeSlots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('renter', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='parking_slots', to='home.rentee')),
                ('slot_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.parkingslots')),
                ('time_slot', models.ManyToManyField(to='home.timeslots')),
            ],
        ),
    ]
