# Generated by Django 4.0.4 on 2022-04-26 09:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_timeslots_parkingtimeslots'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parkingtimeslots',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='parkingtimeslots',
            name='time_slot',
            field=models.CharField(choices=[(0, 'James'), (1, 'Jeremy'), (2, 'Alex')], default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
