# Generated by Django 4.0.3 on 2022-04-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_spotowner_owner_info'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='last_login',
            field=models.DateField(null=True),
        ),
    ]
