# Generated by Django 4.0.4 on 2022-04-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_remove_parkingtimeslots_time_slot_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimeSlots',
        ),
        migrations.RemoveField(
            model_name='parkingtimeslots',
            name='time_slot',
        ),
        migrations.AddField(
            model_name='parkingslots',
            name='time_slots',
            field=models.CharField(default=['A', 'B'], editable=False, max_length=256, null=True),
        ),
    ]
