# Generated by Django 4.0.3 on 2022-04-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_alter_parkingslots_time_slots_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parkingslots',
            name='time_slots',
            field=models.CharField(default=['9:00AM-11:00AM', '11:00AM-1:00PM', '1:00PM-3:00PM', '3:00PM-5:00PM'], editable=False, max_length=256, null=True),
        ),
    ]
