# Generated by Django 4.0.3 on 2022-04-27 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_parkingslots_time_slots'),
    ]

    operations = [
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.IntegerField(null=True)),
                ('credit', models.IntegerField(null=True)),
                ('trxID', models.CharField(max_length=20, null=True)),
                ('nid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='home.rentee')),
            ],
        ),
    ]
