# Generated by Django 4.0.3 on 2022-04-15 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_alter_users_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='is_owner',
            field=models.CharField(choices=[('R', 'Rentee'), ('S', 'Spot Owner')], default='user', max_length=10),
        ),
    ]
